### ISSUE TITLE
online indicator dose not work properly

### ISSUE THREAD

**Issue by shubhabanerjee** [Ronak99/Skype-Clone#11]
please check the code through the 13 number video.
The online indicator is not works properly.

**Comment by shubhabanerjee** [comment]
> please check the code through the 13 number video.
> The online indicator is not works properly.

**Comment by shubhabanerjee** [comment]
> please check the code through the 13 number video.
> The online indicator is not works properly.

**Comment by shubhabanerjee** [comment]
> > please check the code through the 14 number video.
> > The online indicator is not works properly.

**Comment by Ronak99** [comment]
Hey @shubhabanerjee, can you please elaborate on the problem you are facing.
Btw, I did notice that the OnlineIndicator did not turn red when someone logged out of the app or when they launched the app.

I have updated the code so that both the issues are resolved.

Feel free to reopen this thread if you are still facing problems.
